import Head from 'next/head'
import { Login } from '../../components/Login'

export default function LoginPage (): JSX.Element {
  return (
    <>
      <Head>
        <title>Portfolio Tomás Herrera | Login</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Login />
      </main>
    </>
  )
}
