import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { Login } from '../../components/Login'
import { getTokenLS } from '../../utils/token'
export const getServerSideProps: GetServerSideProps = async () => {
  const token = getTokenLS()
  if (token) {
    return {
      redirect: {
        destination: '/admin',
        permanent: false,
      },
    }
  }
  return {
    props: {}, // will be passed to the page component as props
  }
}
export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Portfolio Tomás Herrera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Login/>
      </main>
    </>
  )
}
