import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Tomás Herrera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="text-3xl underline bg-slate-900 text-red-700">
          Probando
        </div>
      </main>
    </>
  )
}
