import { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Portfolio Tomás Herrera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="min-h-screen bg-neutral-900 text-white pr-4 pt-16 pl-12 min-[600px]:pl-16 scroll-smooth">
          Probando
        </div>
      </main>
    </>
  )
}

export default Home
